version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysqldb
    networks:
      - mynetwork

networks:
  mynetwork:
